# Generated by Django 5.0.6 on 2024-06-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="thumbnail_logo.png", null=True, upload_to="images/"
            ),
        ),
    ]
