# Generated by Django 5.0.6 on 2024-08-21 11:28

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0014_userpreference_delete_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_modified",
            field=models.DateTimeField(auto_now=True, verbose_name=account.models.User),
        ),
    ]
